const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"球队",
                        "menuJump":"列表",
                        "tableName":"qiudui"
                    }
                ],
                "menu":"球队"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"球队收藏",
                        "menuJump":"列表",
                        "tableName":"qiuduiCollection"
                    }
                ],
                "menu":"球队收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"球队留言",
                        "menuJump":"列表",
                        "tableName":"qiuduiLiuyan"
                    }
                ],
                "menu":"球队留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"球员",
                        "menuJump":"列表",
                        "tableName":"qiuyuan"
                    }
                ],
                "menu":"球员"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"球员收藏",
                        "menuJump":"列表",
                        "tableName":"qiuyuanCollection"
                    }
                ],
                "menu":"球员收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"球员留言",
                        "menuJump":"列表",
                        "tableName":"qiuyuanLiuyan"
                    }
                ],
                "menu":"球员留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"赛事信息",
                        "menuJump":"列表",
                        "tableName":"saishixinxi"
                    }
                ],
                "menu":"赛事信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"赛事信息收藏",
                        "menuJump":"列表",
                        "tableName":"saishixinxiCollection"
                    }
                ],
                "menu":"赛事信息收藏"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"赛事详情",
                        "menuJump":"列表",
                        "tableName":"saishixinxiXiangqing"
                    }
                ],
                "menu":"赛事详情"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"赛事详情收藏",
                        "menuJump":"列表",
                        "tableName":"saishixinxiXiangqingCollection"
                    }
                ],
                "menu":"赛事详情收藏"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
